# Generated by Django 4.1.4 on 2023-01-21 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ratings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ratings",
            name="agent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="profiles.profile",
                verbose_name="Agent rating",
            ),
        ),
        migrations.AddField(
            model_name="ratings",
            name="comment",
            field=models.TextField(blank=True, null=True, verbose_name="Comment"),
        ),
        migrations.AddField(
            model_name="ratings",
            name="rater",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Rating by user",
            ),
        ),
        migrations.AddField(
            model_name="ratings",
            name="rating",
            field=models.IntegerField(
                choices=[
                    (1, "Poor"),
                    (2, "Fair"),
                    (3, "Good"),
                    (4, "Very Good"),
                    (5, "Excellent"),
                ],
                help_text="1=Poor, 2=Fair, 3=Good, 4=Very good, 5=Excellent",
                null=True,
                verbose_name="Rating",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ratings",
            unique_together={("rater", "agent")},
        ),
    ]
