# Generated by Django 4.1.4 on 2023-02-26 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ratings", "0002_ratings_agent_ratings_comment_ratings_rater_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ratings",
            options={"verbose_name": "Rating", "verbose_name_plural": "Ratings"},
        ),
    ]
