# Generated by Django 4.1.4 on 2023-03-20 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
        ("ratings", "0003_alter_ratings_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ratings",
            name="agent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agent_review",
                to="profiles.profile",
                verbose_name="Agent rating",
            ),
        ),
    ]
